### ISSUE TITLE
ReceivingAmqpLink.DisposeMessage disposes incorrect messages

### ISSUE THREAD

**Issue by varunpuranik** [Azure/azure-amqp#111]
In my app, the client receives messages from the server over the ReceivingAmqpLink. Each received message is then Accepted by the client, by calling ReceivingAmqpLink.DisposeMessageAsync with the delivery tag.
However, if multiple messages are received before the first one is Disposed, then only one delivery message is sent to the server. For example, here is the order of events -
- Receive message A
- Receive message B
- Dispose message A
- Dispose message B (server doesn't get this delivery at this time)
- Receive message C
- Dispose message C (server gets delivery of message B!)
- Receive message D
- Dispose message D (server gets delivery of Message C!)

Is the 1st message required to be disposed before the 2nd message is received over one link? Is the above a valid scenario (and possibly a bug in the library), or should the messages only come in order?

**Comment by xinchen10** [comment]
Which server did you use? Does it work as expected if you call the ReceivingAmqpLink.AcceptMessage method?

**Comment by varunpuranik** [comment]
This turned out to be an application side issue, and I was able to resolve it. Closing the issue.
