### ISSUE TITLE
Using AmqpMessage to build up gradually a collection

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-amqp#112]
`AmqpMessage` exposes a factory method `Create(IEnumerable<Data>)` to create `AmqpMessage` with multiple `Data`s. Is it possible to build up an `AmqpMessage` iteratively, rather than providing an entire collection of `Data` objects?

**Comment by xinchen10** [comment]
This method enumerate the collection and create a list internally. Any IEnumerable implementation should work, but if you are asking if the Data sections can be streamed to the remote side without being buffered locally, the answer is no.

**Comment by SeanFeldman** [comment]
> if you are asking if the Data sections can be streamed to the remote side without being buffered locally, the answer is no.

@xinchen10 that's not what I was after. I'm looking to buffer data sections locally.
What I'm after is I want to build up `AmqpMessage` by adding `Data` sections not in a single call, but multiple calls. Reason - a single amqp message has a limit and I want to control what messages are added to a "batch". For a higher-level library there'd be a `TryAdd()` that would either add an equivalent `Data` segment and return true or return false if there's no more capacity.

**Comment by SeanFeldman** [comment]
Thank you @xinchen10 .
I've tried to create `AmqpMessage` with `AmqpMessage.Create(dataList)` and add to `dataList` `Data` objects one by one, but the reported size of the amqp message `SerializedMessageSize` property returns is always the size of the first object.

**Comment by SeanFeldman** [comment]
@xinchen10 I have tried it again and it looks like it's working. The issue must be in the other part of the code I'm working on. Thank you for confirmation.
