### ISSUE TITLE
Forced batching by SendingAmqpLink even when queue doesn't support batching

### ISSUE THREAD

**Issue by damongr-msft** [Azure/azure-amqp#118]
We have a service bus queue with partitioning and duplication detection enabled, we are using MessageSender (with Amqp) and send multiple messages using just single message SendAsync (so no intentional batching). And we get the exception:
System.InvalidOperationException: Batching brokered messages with distinct SessionId, PartitionKey, or MessageId  is not supported for an entity with partitioning and duplicate detection enabled.

Is there a way to force SendingAmqpLink to not batch?

**Comment by xinchen10** [comment]
Are you using MessageSender from the Microsoft.Azure.ServiceBus package? The AMQP library does not batch messages.

**Comment by damongr-msft** [comment]
Yes, I'm using MessageSender from https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/3.0.2 (I'm going to try 3.1.0 soon, but from what I can tell the Amqp MessageSender didn't change much)
And only calling SendAsync with a single message.
Searching for the work batch in the repo seems to bring back quite a bit of stuff from AmqpLink and AmqpSession, although I haven't had enough time to grok the interactions. All I know is that I'm sending single messages and getting an error from service bus that I'm not allowed to batch when I have dup detection and partitioning enabled.

**Comment by xinchen10** [comment]
SessionId/PartitionKey/MessageId are Service Bus specifics. For partitioned entities, messages are routed based on those properties. The error suggests that a message with such property set arrived at a wrong partition. It could be a wrong setting on the client or a failure in service to handle such properties. At the AMQP layer messages are sent individually. It'd better to follow up with the Service Bus SDK team to debug it further.

**Comment by damongr-msft** [comment]
Ok, I believe I've found out what is going on, there was one portion of our code using an older version which wasn't setting the MessageId. If you don't set the MessageId on a service bus queue that has duplication detection enabled, then you get the error even if you send a single message:
**System.InvalidOperationException: Batching brokered messages with distinct SessionId, PartitionKey, or MessageId is not supported for an entity with partitioning and duplicate detection enabled.**

This error is very strange as Batching is not involved and also it seems completely wrong since MessageId is mandatory not that it isn't supported.

Thanks @xinchen10  for looking and letting me know that batching isn't performed by the AMQP library.
