### ISSUE TITLE
Example for Azure Service Bus

### ISSUE THREAD

**Issue by bdangh** [Azure/azure-amqp#12]
Support for .NET Core is great! Is it possible to connect to Azure Service Bus?

**Comment by dstuckims** [comment]
For reference, which Azure ServiceBus features are most important to you?  Sending to EventHubs, Receiving from EventHubs, Sending/Receiving from Queues/Topics, Managing EventHubs, Managing Queues/Topics, or ServiceBus Relay?  If you could rank your top couple of items that would be helpful.

Thanks,
-Dave

**Comment by bdangh** [comment]
We have production service deployed on Azure which use Topics and Queues with sessions (Sending and Receiving), and we considering to move everything to .NET Core in the next version, so some example which use Topics/Subscriptions with sessions would be very useful.

**Comment by jtaubensee** [comment]
Check out our new Service Bus library: https://github.com/azure/azure-service-bus-dotnet

**Comment by ArjunMenonUK** [comment]
@dstuckims  we are using the Azure topic to push data and pull the data from a web job which listens to the topic and do some business logic operations. As of now we are using the .Net TopicClient's "Send" method to push the data and reading using the "Receive" method. Will AMQP improve the performance ?

**Comment by xinchen10** [comment]
For Service Bus, we recommend https://github.com/azure/azure-service-bus-dotnet

Please check out samples and documentation on that project.
