### ISSUE TITLE
Add support for netstandard2.0

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-amqp#120]
Microsoft.Azure.Devices.Client fails with MissingMethodException for the following configuration:

OS, version, SKU and CPU architecture used: Windows10 Enterprise (1803) x64
Application's .NET Target Framework : UWP version 17134, Microsoft.NETCore.UniversalWindowsPlatform 6.1.7

REF: https://github.com/Azure/azure-iot-sdk-csharp/issues/610#issuecomment-420084200 

This is caused by lack of netstandard2.0 / UAP 16299 support.

**Comment by jenoola** [comment]
REF: https://github.com/Azure/azure-iot-sdk-csharp/issues/612
