### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by bbougot** [Azure/azure-amqp#130]
I have setup a bench to test a very high throughput to Azure Service Bus and it seems there is an issue regarding sending batch messages to entry point method:
`Task<Outcome> SendMessageAsync(AmqpMessage message, ArraySegment<byte> deliveryTag, ArraySegment<byte> txnId, TimeSpan timeout)`

Basically my code looks like this and I use azure-service-bus-dotnet to wire-up AMQP:

    private async Task SendPartitionedBatchAsync(IEnumerable<Message> messages)
    {
        var batch = new List<Message>();
        long batchSize = 0;

        foreach (var message in messages)
        {
            if ((batchSize + message.Size) > Helpers.ServiceBusOptions.MaxServiceBusBatchSizeInBytes)
            {
                await QueueClient.SendAsync(batch);

                batch = new List<Message> {message};
                batchSize = message.Size;
            }
            else
            {
                batch.Add(message);
                batchSize += message.Size;
            }
        }

        await QueueClient.SendAsync(batch);
    }

Here's the memory profile I see while using Visual Studio analyser:

![capture](https://user-images.githubusercontent.com/8962802/49075004-379d1f80-f236-11e8-9ccd-25404f9abe6d.PNG)

And GC will never collect the objects which are growing insanely fast.

**Comment by xinchen10** [comment]
Not able to reproduce the issue. I called the SendMessageAsync directly in a loop and the memory was stable. Since you are using the servicebus-dotnet library you probably want to post the issue to the servicebus repo. Thank you.
