### ISSUE TITLE
Release 2.4.0

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-amqp#135]
[Release notes](https://github.com/Azure/azure-amqp/releases/tag/v2.4.0) say "breaking changes".
![image](https://user-images.githubusercontent.com/1309622/52752569-9316b800-2fb0-11e9-81b0-1c55b4447fa7.png)

Shouldn't this be then a new major, 3.0?

**Comment by xinchen10** [comment]
For various reasons we do not strictly follow semantic versioning right now. The changes require no app code updates but a recompilation. Sometimes we increment MINOR if the changes are on types that are meant for internal implementation only. I hope after the next major release we can follow semantic versioning.

**Comment by SeanFeldman** [comment]
> For various reasons we do not strictly follow semantic versioning right now.

🙀 

> Sometimes we increment MINOR if the changes are on types that are meant for internal implementation only

That definitely should be a minor 🙂

> I hope after the next major release we can follow semantic versioning.

👍 it would be great to see that happening. It's pretty much a norm these days and those 3 numbers have a substantial meaning. Thanks.

PS: will 2.4.0 show up on NuGet at some point?

**Comment by mikanyg** [comment]
Has this version been published to nuget.org and then de-listed again? I did some package upgrades last week and version 2.4.0 ended up on my machine causing issues with 3rd party framework. You can see the referenced issue causing problems.
