### ISSUE TITLE
Remove annotation properties of output message is not working

### ISSUE THREAD

**Issue by SLdragon** [Azure/azure-amqp#144]
Hi, team,
I try to remove annotation property from output message use the method below:
```
outMessage.MessageAnnotations.Map.TryRemoveValue
```
However, after calling outMessage. GetPayload (), the messasge annotation is reappearing again.

Here is the full test code which modified from the test case “AmqpMessageReceiveResendTest”：

```
	var message = AmqpMessage.Create(new AmqpValue { Value = "Hello, AMQP!" });
	message.MessageAnnotations.Map["key"] = "old";

	// send the message and receive it on remote side
	var payload = message.GetPayload();
	var streamMessage = AmqpMessage.CreateAmqpStreamMessage(new BufferListStream(payload));

	//new OutputMessage for resending with modified sections
	var stream = BufferListStream.Create(streamMessage.ToStream(), AmqpConstants.SegmentSize, streamMessage.Settled);
	stream.Seek(0, System.IO.SeekOrigin.Begin);
	var outMessage = AmqpMessage.CreateOutputMessage(stream, false);
	outMessage.Settled = streamMessage.Settled;
	//explicitly assign
	outMessage.Header.Priority = 99;
	outMessage.DeliveryAnnotations.Map["key"] = "da-update";
	outMessage.MessageAnnotations.Map["key"] = "update";

	var  result = outMessage.MessageAnnotations.Map.TryRemoveValue("key", out string value2);

	// Now the value is null
	var annotationValue1 = outMessage.MessageAnnotations.Map["key"];

	var payload2 = outMessage.GetPayload();

	// Now the value is "old"
	var annotationValue2 = outMessage.MessageAnnotations.Map["key"];
```

As you can see from comments, annotation proprety reapear after calling GetPayload Method.
Not sure whether it is related to the mistake using of MessageAnnotations or just is a bug.

The version is 2.3.7

Thanks for your help!

**Comment by SLdragon** [comment]
Hi, @xinchen10 ,do you know how to solve this problem?

**Comment by xinchen10** [comment]
Per the AMQP spec, message annotations has to be retained when the message is transferred. Properties can be added or updated, but not removed. Ideally the library should fail the TryRemoveValue call but it is not doing now. Why do you need to remove a property? Probably you can update the value to null instead of removing it. For example,
```
outMessage.MessageAnnotations.Map["key"] = null;
```
