### ISSUE TITLE
Question: 5000 max inflight messages

### ISSUE THREAD

**Issue by federicobarera** [Azure/azure-amqp#152]
Hi,

ages ago I've opened an issue on service bus repo, regarding the consumer stop processing messages:
https://github.com/Azure/azure-sdk-for-net/issues/6450

The behavior we experienced is that when the message lock expires, and the message becomes visible again in the bus, the message is not removed from the protocol "in-flight" lists, and if the messages are never released the protocol eventually stops processing further messages after 5000 concurrent connections to subscriber entities have been reached (as per documentation).
I've attached a replica repo to the issue too.

My question is the following:
Is it an intended behavior that, if the message lock expires, the message is not dropped from the list on "in flight" messages/connection?

If that so, why an exception is not thrown as specified in the documentation when more than 5000 messages are requested (https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas)

>Subsequent receive requests are rejected, and an exception is received by the calling code. This quota applies to the combined number of concurrent receive operations across all subscriptions on a topic.

**Note**
The messages **are not** imperatively released `.ReleaseAsync()`, in case of an exception, in order to let the lock timeout expire before the message being visible again for re-processing. This also leverages the oob dequeue count and of course dead lettering after n failed attempts

Thanks

**Comment by xinchen10** [comment]
AMQP has not concept of lock timeouts. If a message is not settled (by calling one of the message operations on AmqpMessageReceiver) it has to be tracked by the session or link. This library has a limit for the maximum number of "in-flight" messages (5000 on the session and 1000 on the link by default) but these limits can be changed by the user of this library.

I don't think the Service Bus SDK track all pending messages and their lock timeouts. It expects the application to call Accept/Reject/Release at some point for all received messages. If that did not happen, most likely the application was not doing that.

I suggest you check the application code and make sure you call Accept/Reject/Release for every message you received. If that is not the issue, check with the Service Bus team why the SDK does not settle the AMQP messages.

**Comment by federicobarera** [comment]
@xinchen10 thanks for the prompt answer.

I can confirm that us, as ultimate consumer of the service bus library, tried not to call `Abandon` on exception, under incorrect assumption the service bus library would automatically `Abandon` the message in the protocol once the lock timeout expired, or at least, throw back an exception when tried to retrieve the 5000 + n message.

I guess at this stage the following line from documentation, refers to something else, since we are not receiving any exception:

![image](https://user-images.githubusercontent.com/6658124/74855089-1e4f2a00-5338-11ea-803f-8b8418c8dece.png)

**Comment by xinchen10** [comment]
Yes. the concurrent receive request limit on a messaging entity is a Service Bus service specific setting. It just happens to be 5000. When you say on exception, I assume you mean some error encountered while you process the message. In that case you still have to call one of the message operations to update the message state. As far as I know the Service Bus SDK does not actively track the lock timeout and auto-abandon the message once it expires.

**Comment by federicobarera** [comment]
Thanks, that was very helpful!
