### ISSUE TITLE
Cannot access a disposed object. Object name: 'AmqpBodyStreamMessage'

### ISSUE THREAD

**Issue by bikamani** [Azure/azure-amqp#154]
When try to send a message (SendMessageAsync), seeing this exception of disposed object:
{"Cannot access a disposed object.\r\nObject name: 'AmqpBodyStreamMessage'."}

This happens in two scenarios
1. When network is disconnected manually before sending next message - In this case I assume this should be set to some AmqpErrorCode as I do not see it.
2. Also able to repro this with network connected intermittently retrying SendMessageAsync. (I also found reference [issue](https://github.com/App-vNext/Polly/issues/646))

**Comment by xinchen10** [comment]
The library does not dispose user created messages. I suggest you check if your code disposes a message and later re-send it due to retry.
