### ISSUE TITLE
AmqpMap to JSON

### ISSUE THREAD

**Issue by quintenp** [Azure/azure-amqp#156]
Does anyone know if this functionality readily exists somewhere? 

I had a look around and cant seem to find anything.  I have a client-service subscribed to a Azure service bus, messages are coming in as Dictionary<string, object>.  

Any nested inner objects are AmqpMap I would like to convert it to json, any ideas before I deep dive a custom parser? 

(I do not have control over the sender so I cannot request content-type / message format)

**Comment by xinchen10** [comment]
I do not have the direct answer to your question. AmqpMap is a class derived from Dictionary<MapKey, object>. Can that be handled by some JSON library?
