### ISSUE TITLE
Connection timeout issue when running inside docker container + service fabric

### ISSUE THREAD

**Issue by luisgepeto** [Azure/azure-amqp#157]
I am getting the following exception whenever trying to connect to an Azure Service Bus queue from a process running inside a container in my service fabric cluster. This is only happening inside the cluster and does not occur in my machine. After a couple of retries the connection is stablished succesfully, but it takes ~ 10 min for it to do so.

>Microsoft.Azure.ServiceBus.ServiceBusTimeoutException: The operation did not complete within the allocated time 00:00:59.9999914 for object tls12. ---> System.TimeoutException: The operation did not complete within the allocated time 00:00:59.9999914 for object tls12.
>   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
>   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
>   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
>   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.HandleTransportOpened(IAsyncResult result)
>   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.OnTransportOpened(IAsyncResult result)
>--- End of stack trace from previous location where exception was thrown ---
>   at Microsoft.Azure.ServiceBus.ServiceBusConnection.CreateConnectionAsync(TimeSpan timeout)
>   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject1.OnCreateAsync(TimeSpan timeout)
>   at Microsoft.Azure.Amqp.Singleton1.GetOrCreateAsync(TimeSpan timeout)
>   at Microsoft.Azure.Amqp.Singleton1.GetOrCreateAsync(TimeSpan timeout)
>   at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
>   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.CreateLinkAsync(TimeSpan timeout)
>   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject1.OnCreateAsync(TimeSpan timeout)
>   at Microsoft.Azure.Amqp.Singleton1.GetOrCreateAsync(TimeSpan timeout)
>   at Microsoft.Azure.Amqp.Singleton1.GetOrCreateAsync(TimeSpan timeout)
>   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
>   --- End of inner exception stack trace ---
>   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
>   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass64_0.<<ReceiveAsync>b__0>d.MoveNext()
>--- End of stack trace from previous location where exception was thrown ---
>   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func1 operation, TimeSpan operationTimeout)
>   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func1 operation, TimeSpan operationTimeout)
>   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout)
>   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)
>   at Microsoft.Azure.ServiceBus.MessageReceivePump.<MessagePumpTaskAsync>b__11_0()

**Comment by xinchen10** [comment]
Hi, have you found the problem? The exception message says that the failure is in completing the TLS handshake within 1 minute. Once the connection is established, do you see failures from other API calls? If it only happens in the container setup, it should be something outside of the library.
