### ISSUE TITLE
FaultTolerantAmqpObject<SendingAmqpLink>.TryGetOpenedObject (out T openedAmqpObject) Failures and recovery recommendations.

### ISSUE THREAD

**Issue by azabbasi** [Azure/azure-amqp#167]
Hello

We use the Microsoft.Azure.Amqp library for all AMQP related operation for Microsoft.Azure.Devices client library.

We have been getting some issues logged against us regarding the SendAsync operation
You can see the code here:
https://github.com/Azure/azure-iot-sdk-csharp/blob/master/iothub/service/src/AmqpServiceClient.cs

As part of instantiation for this client, we use FaultTolerantAmqpObject<SendingAmqpLink> object to get opened Sending link and it occasionally fails and that causes the service client to be in a useless state and we have been recommending that our customers dispose their current client and instantiating a new one to get around the issue. 

We would like to know more about the reasons behind failures on [this operation](https://github.com/Azure/azure-iot-sdk-csharp/blob/6ef57a6a26bbfacf06188ac0e48849135d0920b1/iothub/service/src/AmqpServiceClient.cs#L270)
Further more, if this is something that is expected, what are the recommendations for us in handling such scenarios? should we retry the `TryGetOpenedObject` operation? is there anyway to recover from such failures?

We would really appreciate any help with this as we have customers blocked by this issue at the moment.

**Comment by xinchen10** [comment]
TryGetOpenedObject returns false if there is no link created or the link is already closed. In that case you call GetOrCreateAsync to get a new link.
