### ISSUE TITLE
Expose the error reason when throwing System.OperationCanceledException: 'The AMQP object sessionX is aborted.'

### ISSUE THREAD

**Issue by felipepessoto** [Azure/azure-amqp#175]
How to reproduce: Create a IotHub with private network, or disable the public network access:

![image](https://user-images.githubusercontent.com/1336227/103426045-50a2f800-4b95-11eb-91e1-fe15909a524b.png)

Use this sample code: https://github.com/Azure/azure-sdk-for-net/tree/master/samples/iothub-connect-to-eventhubs
You can download my repro here: [ReproIotHubException.zip](https://github.com/Azure/azure-amqp/files/5758303/ReproIotHubException.zip)

The call AmqpSession.OpenAsync immediately fails with the exception: System.OperationCanceledException: 'The AMQP object sessionX is aborted.'

From the Exception message I can't say if the error is transient (should I try again in a few seconds?) or permanent.

Using the Amqp source code, I can see you have this information:

![image](https://user-images.githubusercontent.com/1336227/103426212-8b596000-4b96-11eb-9182-fa71e8d6cbb6.png)

We need to expose this in the Exception details. Or change the Exception type.

Kudos to @bikamani who help me find this information

Thanks.

**Comment by felipepessoto** [comment]
It seems the library actually tries to expose it:

![image](https://user-images.githubusercontent.com/1336227/103426421-3a4a6b80-4b98-11eb-8a4b-1f25e63af512.png)

But when it calls the HandleCloseCommand() method, it ends up calling Abort() in another object, which TerminalException is null:

![image](https://user-images.githubusercontent.com/1336227/103426730-46cfc380-4b9a-11eb-9719-85c9ee3ea469.png)

Which throws the OperationCancelledExceptions:

![image](https://user-images.githubusercontent.com/1336227/103426747-6ff05400-4b9a-11eb-9575-73577a0cc78c.png)

Ignoring the previous AmqpException

**Comment by felipepessoto** [comment]
Changing the Abort method to something like:

![image](https://user-images.githubusercontent.com/1336227/103427060-fad24e00-4b9c-11eb-9789-1252b50c0b2c.png)


![image](https://user-images.githubusercontent.com/1336227/103427091-2c4b1980-4b9d-11eb-906e-c7159b7f5e6f.png)

![image](https://user-images.githubusercontent.com/1336227/103427124-7a601d00-4b9d-11eb-95ba-54e14769f228.png)


Does the tricky, but obviously this is a naive implementation

**Comment by xinchen10** [comment]
OperationCanceledException is retriable in this case. This error happens at the connection layer so you can get it from connection.TerminalException. The connection object is also available on the session object.

**Comment by felipepessoto** [comment]
Cool thanks! I can check if connection.TerminalException is != null and throw it instead.

If you think it makes sense, I would suggest to include it as InnerException.
