### ISSUE TITLE
[Feature Request] Cancellation Token Support

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-amqp#181]
# Problem statement

As asynchronous code has become mainstream in the .NET ecosystem, the [task-based pattern](https://docs.microsoft.com/dotnet/standard/asynchronous-programming-patterns/task-based-asynchronous-pattern-tap) has become the dominant approach.  One of the common practices within the task-based pattern is API support for cancellation of an operation using a `CancellationToken` as the signal.  Across the API surface of the .NET BCL is consistent support for cancellation, which has become an expectation of .NET developers.  Cancellation support has propagated to many of the popular libraries in the ecosystem, including the current generation of Azure SDKs.

The `Microsoft.Azure.Amqp` library does not support cancellation, instead using a timeout-based approach to ensure that an operation does not run unconstrained.  If the operation has not completed naturally within the timeout period, it is aborted by the library.  This timeout-based pattern makes it difficult for consumers of the library to support cancellation in a consistent and deterministic manner.  It also forces applications to balance the trade-off of using a shorter timeout than would be desirable during normal operation against the risk of being unresponsive for longer periods in exceptional cases.

In order for consumers of the AMQP library to offer support for cancellation within their API, it is highly desirable that the AMQP library offer it as part of its API surface.

# Potential workarounds

It has been suggested that consumers of the AMQP library could approximate support for cancellation by closing AMQP links or connections, which would terminate the active operation without negatively impacting the delivery state of messages or corrupting the global state of the AMQP library.  This approach is potentially reasonable for some scenarios, like responding to an application shutdown, but does not apply well to others.

Some of the shortcomings are:

  - The approach to cancellation differs from that of a timeout.  This may (or may not) lead to a different state within the library or manifest as a different experience for consumers.  Efforts would need to be made to ensure that the experience does not drift over time.

  - Closing AMQP objects would impose a performance penalty in the case where the application wishes to cancel one operation and perform another.  For example, assume an application is sending a message and needs to react to a high priority event by sending a different message.  The application would need to cancel the current operation, reopen the connection or link, and then send the new message.  This is likely to be noticeably slower than aborting the operation and then immediately sending the new message using the existing link.

  - Consumers with state associated with an existing link would either be unable to cancel or would otherwise have a degraded experience.  For example, Azure Service Bus associates the lock token for a message with the specific AMQP link from which it was received.  If a receive operation is cancelled and the link closed, applications would be unable to settle any message that they had previously received from that link.

  - For an application-facing library using the AMQP library internally, such as the Azure Service Bus SDK, it is often not possible to determine the context of cancellation in order to make informed decisions.  For example, if an application cancels a receive operation, the Service Bus SDK does not have awareness of whether the application is shutting down or will continue to run.

# Desired outcome

- Cancellation tokens are supported in all asynchronous members of the AMQP library's public API and respected through the implementation for all operations.

- Cancellation requests via the token should be respected as soon as it it safe to do so, ideally superseding the timeout and allowing early termination of the operation.

- Cancellation via token has the same experience for callers as cancellation via timeout.

- Cancellation via token offers similar performance and memory allocation characteristics as cancellation via timeout.

# Products requesting the feature

- [Azure Event Hubs client library for .NET](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs)
- [Azure Service Bus client library for .NET](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Azure.Messaging.ServiceBus)

**Comment by jsquire** [comment]
//cc: @danielmarbach, @JoshLove-msft , @xinchen10

**Comment by timtay-microsoft** [comment]
The Azure IoT Hub SDK team also would really like to see this feature added for the same reasons.
