### ISSUE TITLE
Nuget dependencies

### ISSUE THREAD

**Issue by kvpt** [Azure/azure-amqp#203]
Hi,

The [nuget dependencies ](https://www.nuget.org/packages/Microsoft.Azure.Amqp/#dependencies-tab) are only .NETStandard 1.3.
That cause a lot of packages to be retrieved when targeting higher runtime platform like .NETStandard 2.0 or .NET 5.0.
Is it possible to add an ItemGroup only for NetStandard 2.0 to the csproj of the 2.x branch like in master branch.
The project is already build for NETStandard 2.0 so it should be transparent.

**Comment by xinchen10** [comment]
Added empty dependency sections in nuspec for targets other than netstandard1.3. Please check out release 2.5.8.
