### ISSUE TITLE
AmqpCbsLink class does not support CancellationToken

### ISSUE THREAD

**Issue by azabbasi** [Azure/azure-amqp#207]
Thank you guys so much for adding support for `CancellationToken` across the library. We have gone through the effort to replace all our `TimeSpan timeouts` with `CancellationToken`s
The one place we noticed a lack of support for it is in the `AmqpCbsLink` class. 
It would be awesome if this class also supports cancellation tokens.

**Comment by xinchen10** [comment]
Available in release 2.5.8
