### ISSUE TITLE
Method Not found

### ISSUE THREAD

**Issue by nickticket2u** [Azure/azure-amqp#209]
In azure functions, 
I'm getting this error Method not found: 'System.Threading.Tasks.Task1<Microsoft.Azure.Amqp.Framing.Outcome> Microsoft.Azure.Amqp.SendingAmqpLink.SendMessageAsync(Microsoft.Azure.Amqp.AmqpMessage, System.ArraySegment1, System.ArraySegment`1, System.Threading.CancellationToken)'

The same message appear when calling ServiceBusSender's SendMessageAsync, SendMessagesAsync

Azure.Messaging.ServiceBusis updated to 7.4.0

Sorry for being so vague, but I just couldn't figure out why it was working before and now it doesn't. Something is telling me there's some breaking changes at Azure's side.

Any help or hint would be greatly appreciated

**Comment by xinchen10** [comment]
If you still have this issue, it would be better to report it to the Azure SDK team so they can check if the package is referenced correctly.
