### ISSUE TITLE
New release for deadlock fix

### ISSUE THREAD

**Issue by tlecomte** [Azure/azure-amqp#211]
Would it be possible to get a new release of azure-amqp so that downstream projects (such as Azure sdk libs) can benefit from the fox from https://github.com/Azure/azure-amqp/pull/205 please ? Thanks!

**Comment by xinchen10** [comment]
The change is included in release 2.5.8 but it is only available for netstandard targets. The task creation option is not available for net45. We cannot update to net46 without a breaking change.
