### ISSUE TITLE
Client receivers draining credit should receive an acknowledging flow frame

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-amqp#219]
When a receiver sends a flow frame with `drain: true`, it would be ideal if the broker would send an acknowledging flow frame with `drain: true` set so we know the peer received our drain request.

The [spec](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-flow-control) says this is a SHOULD, so while the existing behavior is technically correct, sending the ack would be an improvement and consistent with service bus.

**Comment by xinchen10** [comment]
Which broker is this issue for?

**Comment by jhendrixMSFT** [comment]
This was observed using the [test broker](https://github.com/Azure/azure-amqp/tree/master/test/TestAmqpBroker).  Does this imply that ack'ing a drain is handled at the broker level, not the protocol level?

**Comment by xinchen10** [comment]
Broker has to implement the credit management required by the drain behavior. Currently the test broker does not support it.

**Comment by xinchen10** [comment]
Added this support to the test broker.

**Comment by jhendrixMSFT** [comment]
https://github.com/Azure/azure-amqp/commit/53efc8a94ee1b173c42bbb08409703e9dffa6101
