### ISSUE TITLE
Need a way to drain receive link when closing

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-amqp#229]
In Service Bus, we would like to be able to drain a link before closing to prevent messages that are in-flight from remaining locked. This can be done for non-Prefetch mode by calling IssueCredit, but there is no way to do this for Prefetch mode.

Apart from the issue with Prefetch, using IssueCredit requires adding an arbitrary delay after the call returns and is therefore not deterministic. It would be better if there was an async API that returns when the draining is complete.

**Comment by Scarlettliuyc** [comment]
Hi team, any updates for this issue? Do we have the plan to fix it?
Thanks

**Comment by Scarlettliuyc** [comment]
HI @xinchen10 , could we confirm whether we have plan to fix this issue? May be in a few months or in one year. 
We know the AMQP level issue need longer time to fix, just want to know the ETA. Thank you in advanced.
