### ISSUE TITLE
A legacy mode value is found in the `Source`'s `Filter` when creating a session receiver using `accept_next_session`

### ISSUE THREAD

**Issue by minghuaw** [Azure/azure-amqp#232]
This is a follow-up to #231. Though the service now accepts a described value as the `SessionFilter`, when creating a session receiver using `accept_next_session` (ie. letting the service decide the session ID), the `Attach` sent from the service to client still carries a legacy mode `SessionFilter` (ie. a non-described string). 

I would imagine this may introduce incompatibilities to existing client SDKs, so I am just curious whether this would be fixed in the near future?

**Comment by mario-guerra** [comment]
@xinchen10 could you please look into this issue and help answer Michael's question? He's helping us develop an AMPQ-compatible service bus crate for the Rust SDK and this issue has come up during development.

**Comment by xinchen10** [comment]
I have informed the service team about this issue. I will follow up with them for possible solutions but given that changing the type will break the existing clients, it is going to be tricky.

**Comment by mario-guerra** [comment]
@xinchen10 thank you.

**Comment by minghuaw** [comment]
I already have an implementation that could work with the legacy format. I could totally adopt this implementation if it is going to be tricky

**Comment by mario-guerra** [comment]
Hi @xinchen10, have you received any feedback from the service team regarding potential solutions to this issue?

**Comment by xinchen10** [comment]
The service team is aware of this issue. If you need further assistance, please contact them under the service bus sdk repo.
