### ISSUE TITLE
Inquiry on the use of AMQP Session in Event Hub SDKs

### ISSUE THREAD

**Issue by minghuaw** [Azure/azure-amqp#244]
It seems like a new AMQP session is created for every new AMQP sender/receiver link in the dotnet/go/java SDKs. I was wondering if there is any particular reason for this design?

I've had a brief discussion on the dotnet SDK repo (Azure/azure-sdk-for-net#34948), but there doesn't seem to be a clear reason.

Thanks in advance :)

**Comment by minghuaw** [comment]
Thanks. Does this reasoning also apply to the Event Hubs SDK?

**Comment by xinchen10** [comment]
Yes
