### ISSUE TITLE
[Question] Why do we need a timer in ReceiveAsyncResult?

### ISSUE THREAD

**Issue by Shazhko-Artem** [Azure/azure-amqp#249]
Could you please explain why you need a [timer ](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L829)in class [`ReceiveAsyncResult`](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L678)? The `ReceiveAsyncResult` class has a [`CompleteInternal `](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L802)method that starts the message processing mechanism. This method is called by two methods [`Signal`](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L797) and [`OnTimer`](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L829). If everything is clear with the `Signal` method - it is called when a message arrives in the queue, then with the `OnTimer` method, everything is not so obvious.

It can also be seen that in the [`Initialize`](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L720) method, we have the functionality to disable the timer when the value of `this.timeout` is `TimeSpan.MaxValue`. But for some reason, in the [Azure.Messaging.ServiceBus](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.5.0/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryOptions.cs#L111) package, a validation was added within which it is impossible to specify the `TimeSpan.MaxValue` value to disable the timer, so I will also ask them a question.

I would be very grateful if you could explain the main function of this timer. This will allow us to better understand how your package works and create better products based on this library.

**Comment by xinchen10** [comment]
Receive operation can optionally has a timeout, which is really the wait time the caller wants to wait if no message is available within the said time duration. This timer implements that behavior.

**Comment by Shazhko-Artem** [comment]
@xinchen10 Thank you very much for your reply. The fact that [timeout](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L829) is really the wait time the caller wants to wait if no message is available within the said time duration is understandable. But it's not entirely clear what this is for. I assume that this functionality is used to handle situations when, for some reason, there is a message in the queue, but the [`Signal`](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L797) mechanism does not work and therefore there is a timer that will forcefully read messages from the queue - but is it possible that the [`Signal`](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L797) mechanism would not work "? If this is a very real situation, could you please tell me exactly how this can happen and if can I reproduce it?

Or is this timer not designed to process messages in the queue, which for some reason were not read by the [`Signal`](https://github.com/Azure/azure-amqp/blob/aa887d026f903d408402e6c6e64c300d75595acd/Microsoft.Azure.Amqp/Amqp/ReceivingAmqpLink.cs#L797) mechanism?

I would be incredibly grateful if you could give an example of when this timer functionality is needed, it would help a lot.

**Comment by xinchen10** [comment]
This timer has two purposes:
1. Complete the receive operation after wait time if no message is available. This part is easy to understand.
2. If `requestedMessageCount` is greater than 1, wait a very short period of time (e.g. 20ms) when the first message is added by `Signal`. This part is not very obvious.

Amqp has no built-in message batching feature but there is a requirement of `ReceiveBatch` API. The batching behavior is implemented in the library using the timer as mentioned above.

**Comment by Shazhko-Artem** [comment]
Thanks a lot, now it's a bit clear.
