### ISSUE TITLE
ReceiveMessagesAsync can return null under heavy load

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-amqp#254]
ReceivingAmqpLink.ReceiveMessagesAsync can return null under heavy load. This was found due to the Azure.Messaging.ServiceBus library's ServiceBusReceiver.ReceiveMessagesAsync method occasionally throwing a NullReferenceException. 
This can be patched up in the Service Bus library, but it would affect all consuming libraries, so it should be fixed in the AMQP library.

**Comment by danielmarbach** [comment]
I haven't only glanced at the code a bit and did not spend much time on this so it might be incorrect. By looking briefly at the code it seems for effiency reasons the ReceiveAsyncResult leaves the `messages`  field null and lazy initializes it. This can lead to `thisPtr.messages` to return null. Master guards against that case already but the hotfix branches don't.

I have added a [draft PR](https://github.com/Azure/azure-amqp/pull/255) that could fix it.

What's also possible is that the caller of `Signal` with the messages list should actually hold a lock on the `SyncRoot` similar to what `Add`  already assumes. Nonetheless guarding against the field not being initialized seems to be a good idea.
