### ISSUE TITLE
Is it possible to release the last version in NuGet

### ISSUE THREAD

**Issue by PejmanNik** [Azure/azure-amqp#256]
Hi, the last published version in NuGet differs from the last version in the repository. for instance, the WebSocketTransportSettings don't have the `CreateListener` method:

```
#region Assembly Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// \.nuget\packages\microsoft.azure.amqp\2.6.4\lib\netstandard2.0\Microsoft.Azure.Amqp.dll
// Decompiled with ICSharpCode.Decompiler 8.1.1.7464
#endregion
...
public sealed class WebSocketTransportSettings : TransportSettings
{
     ...

    public override TransportListener CreateListener()
    {
        throw new NotSupportedException();
    }
}
```

Is it possible to release the last version in NuGet? 
Thank you

**Comment by xinchen10** [comment]
NuGet package was released from the hotfix branch, which does not support websocket listener for netstandard targets as of now.
