### ISSUE TITLE
Getting a ton of SocketException after upgrading to .net8

### ISSUE THREAD

**Issue by ogauthier** [Azure/azure-amqp#257]
The processor just keeps throwing SocketExceptions with this message:

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

On method: Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope+<CreateAndOpenConnectionAsync>d__80.MoveNext

Once we rollback to .net 7, all theses exception disappear.

**Comment by xinchen10** [comment]
I tested connecting to an Azure messaging service directly using the library (version 2.6.4) on .NET 8. It was working.

**Comment by xinchen10** [comment]
This is the code I tested.
```
using Microsoft.Azure.Amqp;

var factory = new AmqpConnectionFactory();
for (int i = 0; i < 1000; i++)
{
    var connection = await factory.OpenConnectionAsync("amqps://mynamespace.servicebus.windows.net");
    await connection.CloseAsync(CancellationToken.None);

    Console.WriteLine($"{i}: connection opened and closed");
}
```
