### ISSUE TITLE
Exception receiving messages from Azure Service Bus in Xamarin.iOS

### ISSUE THREAD

**Issue by mintyfusion** [Azure/azure-amqp#71]
I'm using the new Azure Service Bus component which is available here: https://github.com/azure/azure-service-bus-dotnet

When running this package in .NET Core 1.1, the message is received absolutely fine. Using the same code in Xamarin.iOS, it throws an exception on receive.

{System.InvalidOperationException: Operation is not valid due to the current state of the object.
  at Microsoft.Azure.Amqp.Transport.TransportStream.Write (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00001] in <e383a3b5ed164d37aa1edf820d88dc4b>:0 
  at Mono.Net.Security.MobileAuthenticatedStream.InnerFlush () [0x0000e] in

**Comment by xinchen10** [comment]
This is a known issue that we are fixing. The fix should be available in a couple of days. Thanks for reporting the issue.

**Comment by mintyfusion** [comment]
Thank you. Looking forward to this fix, as it's blocking us.

**Comment by jeremejevs** [comment]
@xinchen10 What's the status on this? Is there maybe a temporary workaround you could suggest?

**Comment by mintyfusion** [comment]
@xinchen10 Any update on when the fix will be available?

**Comment by xinchen10** [comment]
We have released a new version of this library. I think the Service Bus SDK team is picking up the new version but I don't know exactly when it will be available.

**Comment by mintyfusion** [comment]
@xinchen10 Thank You very much and really appreciate for the quick turnaround. I don't see the package update here, is that also happening?

**Comment by xinchen10** [comment]
Version 2.1.0 is available on NuGet https://www.nuget.org/packages/Microsoft.Azure.Amqp/

**Comment by mintyfusion** [comment]
Thank You very much.
