### ISSUE TITLE
Web Proxy Settings

### ISSUE THREAD

**Issue by cjpomer** [Azure/azure-amqp#73]
I'm here because I'm trying to figure out how to use azure-service-bus-dotnet (in netcore) behind a web proxy.

My issue is that I would like to use HTTP with TLS, but I am behind an authenticating web proxy.  I don't see how to configure e.g. the `TlsTransport` to work behind a web proxy.  I came expecting to find a 
`WebRequest` somewhere under the hood, but I see AMQP is lower level and has tight performance concerns.

Is there a way to configure `TlsTransport` such that it this AMQP library can be used in an enterprise env. with a proper web proxy?

Thanks!

**Comment by xinchen10** [comment]
@cjpomer it is not supported with the current implementation. To enable that we need to expose the underlying client web socket options through the web socket transport settings.

**Comment by xinchen10** [comment]
It is available in 2.0.0.
