### ISSUE TITLE
AmqpObject.State should be thread safe

### ISSUE THREAD

**Issue by nemakam** [Azure/azure-amqp#77]
`AmqpObject.State` currently is a property on the object which is used to to implement methods like `IsClosed()`. Unless these are thread safe, they might not return the latest value. One of `volatile`/`interlocked`/`lock` should be used for this property.
Similar to https://github.com/Azure/azure-service-bus-dotnet/issues/297 

Sample code where this becomes an issue:

```c#
while (timeoutHelper.RemainingTime() > TimeSpan.Zero)
{
	IEnumerable<AmqpMessage> amqpMessages = null;
	var hasMessages = await Task.Factory.FromAsync(
		(c, s) => receiveLink.BeginReceiveRemoteMessages(maxMessageCount, DefaultBatchFlushInterval, timeoutHelper.RemainingTime(), c, s),
		a => receiveLink.EndReceiveMessages(a, out amqpMessages),
		this).ConfigureAwait(false);
	Exception exception;
	if ((exception = receiveLink.GetInnerException()) != null)
	{
		throw exception;
	}

	if (receiveLink.IsClosing())
	{
		break;
	}
}
```

In the above case, receiveLink.IsClosing() will not return true if the link (through linkManager) is closed on a different thread.

**Comment by xinchen10** [comment]
Receive now throws when the link is closed.
