### ISSUE TITLE
The AMQP library should not define .NET Framework types: ICloneable

### ISSUE THREAD

**Issue by CIPop** [Azure/azure-amqp#87]
Getting the following error if I compile an UWP 16299 application also importing AMQP:

```
Error	CS0433	The type 'ICloneable' exists in both 'Microsoft.Azure.Amqp, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```

The code is in: https://github.com/Azure/azure-amqp/blob/bb20e964c18fb737f801d2584ae9b6cabd55060e/Microsoft.Azure.Amqp/PlatformSupport.cs

**Comment by CIPop** [comment]
Thanks @xinchen10 for the fix! Should this be fixed now?

**Comment by xinchen10** [comment]
It should be fixed (in develop branch). I removed ICloneable from the code. We do not have a date for releasing a new NuGet package yet.
