### ISSUE TITLE
Calling AMPQLite's TestAmqpBroker

### ISSUE THREAD

**Issue by MatthewDavidCampbell** [Azure/azure-amqp#93]
Using 2.1.3 of Azure AMQP on dotnet 2.1.4 (Windows 10)

Not well versed in the AMQP protocol and what brokers Microsoft's AMQP supports but thought I could run local broker [TestAmqpBroker](https://github.com/Azure/amqpnetlite/blob/master/test/Common/TestAmqpBroker.cs) from AMQP Lite.  Trying the following setup:

     var transportSettings = new TcpTransportSettings() {
       Host = "127.0.0.1",
       Port = 5672
     };

     var settings = new Microsoft.Azure.Amqp.AmqpSettings();

     AmqpTransportProvider amqpProvider = new AmqpTransportProvider();
     amqpProvider.Versions.Add(new AmqpVersion(new Version(1, 0, 0, 0)));
     settings.TransportProviders.Add(amqpProvider);

     AmqpTransportInitiator initiator = new AmqpTransportInitiator(settings, transportSettings);
      TransportBase transport = await Task.Factory.FromAsync(
                (c, s) => initiator.BeginConnect(AmqpConstants.DefaultTimeout, c, s),
                (r) => initiator.EndConnect(r),
                null)
                .ConfigureAwait(false);

     AmqpConnectionSettings connectionSettings = new AmqpConnectionSettings()
     {
        ContainerId = Guid.NewGuid().ToString(),
        MaxFrameSize = 65536,
        HostName = "127.0.0.1"
     };

     AmqpConnection connection = new AmqpConnection(
       transport, 
       ProtocolHeader.Amqp100, 
       false, 
       settings, 
       connectionSettings
     );
     await connection.OpenAsync(AmqpConstants.DefaultTimeout).ConfigureAwait(false);

Fails on handling the max frame size from the test broker which is set to 65536 but the `AsyncIO` receives 1095586128.  Not sure where 1095586128 comes from.  But thinking that the response form TestAmqpBroker on open isn't getting parsed correctly thus yielding an incorrect frame size to the `HandleFrameSizeReadComplete` handler.

Wondering first if talking with another AMPQ broker other than an Azure is possible and if I can configuring the underlying connection wrong?  By the way, the initiator is flagged to false.  If it is true then the connection closes immediately.

**Comment by xinchen10** [comment]
For client connection the initiator flag should be true. The connection closes because the amqpnetlite's test broker does SASL by default but the client starts with AMQP version negotiation. It is much easier to use AmqpConnectionFactory to open a connection. 

Start the test broker
```
TestAmqpBroker.exe amqp://localhost:5672 /trace:frame
```

The following code should work.
```
TimeSpan timeout = TimeSpan.FromSeconds(60);
AmqpConnectionFactory factory = new AmqpConnectionFactory();
var connection = await factory.OpenConnectionAsync(
    new Uri("amqp://localhost:5672"),
    new SaslAnonymousHandler(),
    timeout);
var session = connection.CreateSession(new AmqpSessionSettings());
await session.OpenAsync(timeout);
var sender = new SendingAmqpLink(
    session,
    new AmqpLinkSettings()
    {
        Role = false,
        LinkName = "test-sender",
        Source = new Source(),
        Target = new Target() { Address = "q1" }
    });
await sender.OpenAsync(timeout);
await sender.SendMessageAsync(
    AmqpMessage.Create(new AmqpValue() { Value = "hello " }),
    AmqpConstants.EmptyBinary,
    AmqpConstants.NullBinary,
    timeout);
await sender.CloseAsync(timeout);
await session.CloseAsync(timeout);
await connection.CloseAsync(timeout);
```

If you start the test broker with user info, it will do SASL PLAIN authentication which will require SaslPlainHandler during connection creation.
```
TestAmqpBroker.exe amqp://localhost:5672 /creds:user:pwd /trace:frame
```

Use SASL PLAIN.
```
TimeSpan timeout = TimeSpan.FromSeconds(60);
AmqpConnectionFactory factory = new AmqpConnectionFactory();
var connection = await factory.OpenConnectionAsync(
    new Uri("amqp://localhost:5672"),
    new SaslPlainHandler() { AuthenticationIdentity = "user", Password = "pwd" },
    timeout);
```

**Comment by MatthewDavidCampbell** [comment]
Thanks for the response @xinchen10.  Tried the anonymous SASL.  Yields a protocol mismatch.  Here is the output from the test broker:

     [DBG]: PS C:\Software\TestAmqpBroker>> .\TestAmqpBroker.exe amqp://127.0.0.1:5672 /trace:frame /queues:q1
     Broker started. Press the enter key to exit...
     [09:15:09.644] SEND AMQP 0 1.0.0
     [09:15:09.662] SEND (ch=0) open(container-id:TestAmqpBroker:f4d4104b,host-name:127.0.0.1,max-frame-size:65536,channel-max:999)
     [09:15:09.678] RECV AMQP 3 1 0 0

which bombs out in the client with:

     Microsoft.Azure.Amqp.AmqpException : The requested protocol version 'AMQP 3 1.0.0' is not supported. The supported version is 'AMQP 0 1.0.0'.

Using the plain with user/pwd causes the connection to close automatically which was my original problem.

But...an azure ampq connection should be (in theory) able to talk with the test broker?

**Comment by xinchen10** [comment]
@MatthewDavidCampbell are you running the TestAmqpBroker executable from the release? There might be some updates after that release. The one you are running does not do SASL Anonymous by default if no user credentials is specified in the command line. The current code in master does.

The error you saw is due to mismatch of SASL config on both sides. Given the current test broker you are running, you can pass null for the SASL handler and it should work. Alternatively you can add `/creds:user:pwd` command line option to run the test broker and use SASL PLAIN handler in the client to make it work.

**Comment by MatthewDavidCampbell** [comment]
@xinchen10 Cloned from master and reran both anonymously as well the plain authentication.  The handshaking still isn't working.  As anonymous the traces from the test broker are:

     PS C:\Users\extmaca\Source\Repos\amqpnetlite\bin\Debug\TestAmqpBroker> .\TestAmqpBroker.exe amqp://localhost:5672 /trace:frame /queues:q1
     Broker started. Press the enter key to exit...
     [09:06:44.136] SEND AMQP 3 1 0 0
     [09:06:44.143] SEND sasl-mechanisms(sasl-server-mechanisms:[ANONYMOUS])
     [09:06:44.193] RECV sasl-init(mechanism:ANONYMOUS,initial-response:...)
     [09:06:44.195] SEND sasl-outcome(code:0)
     [09:06:44.199] SEND AMQP 0 1.0.0
     [09:06:44.200] SEND (ch=0) open(container-id:TestAmqpBroker:df22962d,host-name:localhost,max-frame-size:65536,channel-max:999,idle-time-out:240000)

And the client fails on:

     System.OperationCanceledException : The AMQP object session1 is aborted.

when awaiting the session to open (`await session.OpenAsync(timeout)`).  The connection is apparently closing when Microsoft's AMPQ connection tried to add the session.

Using plain authentication the traces are identical expect that the sasl mechanism is PLAIN but the connection closes before a session can be added.

Here are traces using the AMQP Lite client:

     [09:18:57.514] SEND AMQP 3 1 0 0
     [09:18:57.521] SEND sasl-mechanisms(sasl-server-mechanisms:[PLAIN])
     [09:18:57.542] RECV sasl-init(mechanism:PLAIN,initial-response:...,hostname:127.0.0.1)
     [09:18:57.546] SEND sasl-outcome(code:0)
     [09:18:57.550] SEND AMQP 0 1.0.0
     [09:18:57.556] SEND (ch=0) open(container-id:TestAmqpBroker:dd45c7b1,host-name:localhost,max-frame-size:65536,channel-max:999,idle-time-out:240000)
     [09:18:57.559] RECV AMQP 0 1 0 0
     [09:18:57.562] RECV (ch=0) open(container-id:15786db8-c52a-4042-939e-db9a6b511949,host-name:127.0.0.1,max-frame-size:262144,channel-max:256)
     [09:18:57.565] RECV (ch=0) close()
     [09:18:57.566] SEND (ch=0) close()

There are 2 open calls rather than one so the handshaking differs.

**Comment by xinchen10** [comment]
@MatthewDavidCampbell the code I posted worked fine when I tested it. Let me see what's the difference here.

**Comment by MatthewDavidCampbell** [comment]
@xinchen10 Appreciate the help.  Cool that it worked for you but wondering what the difference is if I pulled the test broker from **master** and still got the issue of the connection closing prematurely.

**Comment by MatthewDavidCampbell** [comment]
@xinchen10 Can you "gist" your configuration?  Would be interesting to see you setup and what base you are running off (i.e. Windows 10, dotnet sdk 2.? etc.).  Thanks in advance.

**Comment by xinchen10** [comment]
I was testing it on full .net and dotnet 1.0. Tried it on dotnet 2.0 and saw the error. It's a bug in this library. It should work now with the bits from master.

**Comment by MatthewDavidCampbell** [comment]
Thanks works.  Big kodos for the help!
