### ISSUE TITLE
TcpTransportInitiator compatibility issue with .net standard

### ISSUE THREAD

**Issue by noahhai** [Azure/azure-amqp#95]
The following code failing when run from AWS lambda:

https://github.com/Azure/azure-amqp/blob/98dc6efb46969bb41de6301d36887417b70c8045/Microsoft.Azure.Amqp/Amqp/Transport/TcpTransportInitiator.cs#L33-L42

But, when I use the monoandroid build (in my .net core application) it works correctly when running from AWS lambda. The issue is the call to Socket.ConnectAsync eventually calls to here:
MultipleSocketMultipleConnectAsync > Socket.OSSupportsIPv4 > Socket.InitializeSockets > UnsafeNclNativeMethods.OSSOCK.WSAStartup

Pretty sure this last method is failing. Workaround to failback to using ipv4 AddressFamily when the non-monoandroid statement fails?

https://github.com/Microsoft/referencesource/blob/b31308b03e8bd5bf779fb80fda71f31eb959fe0b/System/net/System/Net/Sockets/_MultipleConnectAsync.cs#L425

https://github.com/Microsoft/referencesource/blob/b31308b03e8bd5bf779fb80fda71f31eb959fe0b/System/net/System/Net/Sockets/Socket.cs#L5980

**Comment by xinchen10** [comment]
@noahhai do you mean that the full .net version is failing but the monoandroid one is working? Does it work if you run it directly (e.g. from a console app)?

**Comment by noahhai** [comment]
Correct..the .net standard build doesnt seem to be working. When running from a console app on windows, both the .net standard and the monoandroid (I didn't rebuild, just binding redirect) versions work. When running on aws lambda, only the monoandroid build works.

I can also test running a core console app with the standard build on a unix system (not aws lambda).

**Comment by xinchen10** [comment]
Please reopen the issue if you have more details.
